### ISSUE TITLE
How to generate Program Id with specify name

### ISSUE THREAD

**Issue by docongminh** [port-finance/variable-rate-lending#26]
Hi, 
I see your program Id `Port7uDYB3wk6GJAw4KT1WpTeMtSu9bTcChBHkX2LfR` start with `Port`. So, Could you tell me how to generate specify name like `Port` in your Program Id ? 
Thank you !

**Comment by gabRiel-bit20** [comment]
Sure. You can use the this command:
```
solana-keygen grind --starts-with <prefix-that-you-want>:1
```
